export const ADD_TODO = 'ADD_TODO';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';

export const FETCH_USER = 'FETCH_USER';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_ERROR = 'USER_ERROR';

export const GET_INFO = 'GET_INFO';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_ERROR = 'GET_INFO_ERROR';

export const GET_DEPART_DOCTORS = 'GET_DEPART_DOCTORS';
export const GET_DEPART_DOCTORS_SUCCESS = 'GET_DEPART_DOCTORS_SUCCESS';
export const GET_DEPART_DOCTORS_ERROR = 'GET_DEPART_DOCTORS_ERROR';

export const GET_INDIVIDUAL_DOCTOR = 'GET_INDIVIDUAL_DOCTOR';
export const GET_INDIVIDUAL_DOCTOR_SUCCESS = 'GET_INDIVIDUAL_DOCTOR_SUCCESS';
export const GET_INDIVIDUAL_DOCTOR_ERROR = 'GET_INDIVIDUAL_DOCTOR_ERROR';

export const GET_DEPART_NURSES = 'GET_DEPART_NURSES';
export const GET_DEPART_NURSES_SUCCESS = 'GET_DEPART_NURSES_SUCCESS';
export const GET_DEPART_NURSES_ERROR = 'GET_DEPART_NURSES_ERROR';

export const GET_INDIVIDUAL_NURSE = 'GET_INDIVIDUAL_NURSE';
export const GET_INDIVIDUAL_NURSE_SUCCESS = 'GET_INDIVIDUAL_NURSE_SUCCESS';
export const GET_INDIVIDUAL_NURSE_ERROR = 'GET_INDIVIDUAL_NURSE_ERROR';

export const GET_MY_NURSES = 'GET_MY_NURSES';
export const GET_MY_NURSES_SUCCESS = 'GET_MY_NURSES_SUCCESS';
export const GET_MY_NURSES_ERROR = 'GET_MY_NURSES_ERROR';

export const GET_MY_INDIVIDUAL_NURSE = 'GET_MY_INDIVIDUAL_NURSE';
export const GET_MY_INDIVIDUAL_NURSE_SUCCESS = 'GET_MY_INDIVIDUAL_NURSE_SUCCESS';
export const GET_MY_INDIVIDUAL_NURSE_ERROR = 'GET_MY_INDIVIDUAL_NURSE_ERROR';

export const GET_MY_PATIENTS = 'GET_MY_PATIENTS';
export const GET_MY_PATIENTS_SUCCESS = 'GET_MY_PATIENTS_SUCCESS';
export const GET_MY_PATIENTS_ERROR = 'GET_MY_PATIENTS_ERROR';

export const GET_MY_INDIVIDUAL_PATIENT = 'GET_MY_INDIVIDUAL_PATIENT';
export const GET_MY_INDIVIDUAL_PATIENT_SUCCESS = 'GET_MY_INDIVIDUAL_PATIENT_SUCCESS';
export const GET_MY_INDIVIDUAL_PATIENT_ERROR = 'GET_MY_INDIVIDUAL_PATIENT_ERROR';

export const DELETE_MY_INDIVIDUAL_NURSE = 'DELETE_MY_INDIVIDUAL_NURSE';
export const DELETE_MY_INDIVIDUAL_NURSE_SUCCESS = 'DELETE_MY_INDIVIDUAL_NURSE_SUCCESS';
export const DELETE_MY_INDIVIDUAL_NURSE_ERROR = 'DELETE_MY_INDIVIDUAL_NURSE_ERROR';

export const GET_NURSES_DEPARTMENTS = 'GET_NURSES_DEPARTMENTS';
export const GET_NURSES_DEPARTMENTS_SUCCESS = 'GET_NURSES_DEPARTMENTS_SUCCESS';
export const GET_NURSES_DEPARTMENTS_ERROR = 'GET_NURSES_DEPARTMENTS_ERROR';

export const ADD_NURSE = 'ADD_NURSE';
export const ADD_NURSE_SUCCESS = 'ADD_NURSE_SUCCESS';
export const ADD_NURSE_ERROR = 'ADD_NURSE_ERROR';

export const GET_EMAILS_PATIENTS = 'GET_EMAILS_PATIENTS';
export const GET_EMAILS_PATIENTS_SUCCESS = 'GET_EMAILS_PATIENTS_SUCCESS';
export const GET_EMAILS_PATIENTS_ERROR = 'GET_EMAILS_PATIENTS_ERROR';

export const ADD_PATIENT = 'ADD_PATIENT';
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';
export const ADD_PATIENT_ERROR = 'ADD_PATIENT_ERROR';

export const RESET_INDICATORS = 'RESET_INDICATORS';
